
const QUESTION_DB = [
  // =========================
  // LANGUAGE KNOWLEDGE
  // =========================
  {
    id: "language-001",
    topic: "language-knowledge",
    category: "Vocabulary",
    difficulty: "easy",
    question: 'What does "proactive" mean in a workplace context?',
    options: [
      "Waiting for instructions before acting",
      "Taking initiative and acting in advance",
      "Reacting quickly to problems",
      "Following a set schedule",
    ],
    correctAnswer: 1,
  },
  {
    id: "language-002",
    topic: "language-knowledge",
    category: "Grammar",
    difficulty: "easy",
    question: 'Complete the sentence: "Could you please _____ me know when you are available?"',
    options: ["let", "make", "tell", "give"],
    correctAnswer: 0,
  },
  {
    id: "language-003",
    topic: "language-knowledge",
    category: "Grammar",
    difficulty: "easy",
    question: 'Complete: "I am looking forward _____ working with you."',
    options: ["to", "for", "at", "in"],
    correctAnswer: 0,
  },
  {
    id: "language-004",
    topic: "language-knowledge",
    category: "Vocabulary",
    difficulty: "easy",
    question: 'What does "to meet a deadline" mean?',
    options: [
      "To schedule a meeting",
      "To complete work by a specified time",
      "To extend the timeframe",
      "To cancel an appointment",
    ],
    correctAnswer: 1,
  },
  {
    id: "language-005",
    topic: "language-knowledge",
    category: "Vocabulary",
    difficulty: "easy",
    question: 'What is the meaning of "to collaborate"?',
    options: [
      "To work independently",
      "To compete with others",
      "To work together with others",
      "To supervise a team",
    ],
    correctAnswer: 2,
  },
  {
    id: "language-006",
    topic: "language-knowledge",
    category: "Grammar",
    difficulty: "easy",
    question: 'Choose the correct form: "The team _____ working on the project since Monday."',
    options: ["has been", "have been", "is been", "are been"],
    correctAnswer: 0,
  },
  {
    id: "language-007",
    topic: "language-knowledge",
    category: "Idioms",
    difficulty: "easy",
    question: 'What does "think outside the box" mean?',
    options: [
      "To organize things properly",
      "To think creatively and differently",
      "To focus on details",
      "To work in a confined space",
    ],
    correctAnswer: 1,
  },
  {
    id: "language-008",
    topic: "language-knowledge",
    category: "Vocabulary",
    difficulty: "medium",
    question: 'Which word is closest in meaning to "reliable"?',
    options: ["careless", "trustworthy", "temporary", "noisy"],
    correctAnswer: 1,
  },
  {
    id: "language-009",
    topic: "language-knowledge",
    category: "Grammar",
    difficulty: "medium",
    question: 'Choose the correct sentence.',
    options: [
      "She don’t like coffee.",
      "She doesn’t likes coffee.",
      "She doesn’t like coffee.",
      "She not like coffee.",
    ],
    correctAnswer: 2,
  },
  {
    id: "language-010",
    topic: "language-knowledge",
    category: "Grammar",
    difficulty: "medium",
    question: 'Pick the correct option: "If I _____ more time, I would help you."',
    options: ["have", "had", "will have", "has"],
    correctAnswer: 1,
  },
  {
    id: "language-011",
    topic: "language-knowledge",
    category: "Vocabulary",
    difficulty: "medium",
    question: 'What does "to reschedule" mean?',
    options: [
      "To cancel a plan forever",
      "To change a plan to a new time",
      "To agree quickly",
      "To arrive late",
    ],
    correctAnswer: 1,
  },
  {
    id: "language-012",
    topic: "language-knowledge",
    category: "Vocabulary",
    difficulty: "medium",
    question: 'Choose the best word: "We need to _____ this issue before launch."',
    options: ["ignore", "address", "delay", "forget"],
    correctAnswer: 1,
  },
{
id: "language-013",
topic: "language-knowledge",
category: "Vocabulary",
difficulty: "hard",
question: 'In a workplace context, what does "to streamline a process" mean?',
options: [
"To add more steps for safety",
"To make a process more efficient by reducing unnecessary steps",
"To delay decisions until later",
"To assign the process to someone else",
],
correctAnswer: 1,
},
{
id: "language-014",
topic: "language-knowledge",
category: "Vocabulary",
difficulty: "hard",
question: 'What is the best meaning of "stakeholder"?',
options: [
"Someone who owns stock only",
"Anyone affected by or interested in a project’s outcome",
"A person who manages schedules",
"A customer who complains often",
],
correctAnswer: 1,
},
{
id: "language-015",
topic: "language-knowledge",
category: "Grammar",
difficulty: "hard",
question: 'Choose the correct sentence.',
options: [
"Neither of the reports are finished.",
"Neither of the reports is finished.",
"Neither the reports is finished.",
"Neither reports are finished.",
],
correctAnswer: 1,
},
{
id: "language-016",
topic: "language-knowledge",
category: "Grammar",
difficulty: "hard",
question: 'Complete the sentence: "Had we known about the outage earlier, we _____ a backup plan."',
options: ["prepare", "prepared", "would prepare", "would have prepared"],
correctAnswer: 3,
},
{
id: "language-017",
topic: "language-knowledge",
category: "Idioms",
difficulty: "hard",
question: 'What does "to touch base" mean in professional communication?',
options: [
"To physically visit the office",
"To briefly connect or check in with someone",
"To complete a task immediately",
"To argue about details",
],
correctAnswer: 1,
},
{
id: "language-018",
topic: "language-knowledge",
category: "Vocabulary",
difficulty: "hard",
question: 'Which word best fits: "We need a _____ analysis before we commit resources."',
options: ["superficial", "comprehensive", "temporary", "careless"],
correctAnswer: 1,
},
{
id: "language-019",
topic: "language-knowledge",
category: "Grammar",
difficulty: "hard",
question: 'Pick the correct option: "The proposal, along with the supporting documents, _____ on your desk."',
options: ["are", "were", "is", "have been"],
correctAnswer: 2,
},
{
id: "language-020",
topic: "language-knowledge",
category: "Vocabulary",
difficulty: "hard",
question: 'What does "to mitigate a risk" mean?',
options: [
"To accept a risk without changes",
"To reduce the impact or likelihood of a risk",
"To create a new risk",
"To ignore warnings",
],
correctAnswer: 1,
},
{
id: "language-021",
topic: "language-knowledge",
category: "Grammar",
difficulty: "hard",
question: 'Complete: "This is the third time he _____ the same mistake this month."',
options: ["makes", "made", "has made", "is making"],
correctAnswer: 2,
},
{
id: "language-022",
topic: "language-knowledge",
category: "Idioms",
difficulty: "hard",
question: 'What does "to be on the same page" mean?',
options: [
"To read the same document",
"To agree or share the same understanding",
"To work in the same room",
"To be at the same job level",
],
correctAnswer: 1,
},
{
id: "language-023",
topic: "language-knowledge",
category: "Vocabulary",
difficulty: "hard",
question: 'Choose the best meaning of "bandwidth" in a workplace setting.',
options: [
"Internet speed",
"A person’s available time and capacity to take on work",
"A weekly meeting agenda",
"A company’s budget limit",
],
correctAnswer: 1,
},
{
id: "language-024",
topic: "language-knowledge",
category: "Grammar",
difficulty: "hard",
question: 'Choose the correct sentence.',
options: [
"If the client will approve the design, we start development.",
"If the client approves the design, we will start development.",
"If the client approve the design, we will start development.",
"If the client approves the design, we started development.",
],
correctAnswer: 1,
},
{
id: "language-025",
topic: "language-knowledge",
category: "Vocabulary",
difficulty: "hard",
question: 'What does "to escalate an issue" mean?',
options: [
"To solve it quietly alone",
"To raise it to a higher level of attention or authority",
"To postpone it until next week",
"To write a summary about it",
],
correctAnswer: 1,
},
{
id: "language-026",
topic: "language-knowledge",
category: "Idioms",
difficulty: "hard",
question: 'What does "to get the ball rolling" mean?',
options: [
"To finish a project",
"To begin a process or start making progress",
"To avoid responsibility",
"To schedule a break",
],
correctAnswer: 1,
},
{
id: "language-027",
topic: "language-knowledge",
category: "Grammar",
difficulty: "hard",
question: 'Pick the correct option: "By the time you arrive, we _____ the meeting."',
options: ["will start", "will have started", "started", "have started"],
correctAnswer: 1,
},
{
id: "language-028",
topic: "language-knowledge",
category: "Vocabulary",
difficulty: "hard",
question: 'What does "to delegate" mean in a workplace context?',
options: [
"To delay a task until later",
"To give a task or responsibility to someone else",
"To do a task without telling anyone",
"To remove someone from a project",
],
correctAnswer: 1,
},
{
id: "language-029",
topic: "language-knowledge",
category: "Grammar",
difficulty: "hard",
question: 'Choose the correct sentence.',
options: [
"The data were analyzed and shows a clear trend.",
"The data was analyzed and show a clear trend.",
"The data were analyzed and show a clear trend.",
"The data was analyzed and shows a clear trend.",
],
correctAnswer: 2,
},
{
id: "language-030",
topic: "language-knowledge",
category: "Idioms",
difficulty: "hard",
question: 'What does "to raise a red flag" mean?',
options: [
"To celebrate a success publicly",
"To signal that something may be wrong or risky",
"To request a day off",
"To increase the project budget",
],
correctAnswer: 1,
},
  // =========================
  // GENERAL KNOWLEDGE
  // =========================
  {
    id: "general-001",
    topic: "general-knowledge",
    category: "World",
    difficulty: "easy",
    question: "Which planet is known as the Red Planet?",
    options: ["Venus", "Mars", "Jupiter", "Mercury"],
    correctAnswer: 1,
  },
  {
    id: "general-002",
    topic: "general-knowledge",
    category: "Geography",
    difficulty: "easy",
    question: "What is the largest ocean on Earth?",
    options: ["Atlantic Ocean", "Indian Ocean", "Pacific Ocean", "Arctic Ocean"],
    correctAnswer: 2,
  },
  {
    id: "general-003",
    topic: "general-knowledge",
    category: "Science",
    difficulty: "easy",
    question: "Water freezes at what temperature (Celsius)?",
    options: ["0°C", "10°C", "50°C", "100°C"],
    correctAnswer: 0,
  },
  {
    id: "general-004",
    topic: "general-knowledge",
    category: "History",
    difficulty: "easy",
    question: "The pyramids are located in which country?",
    options: ["Mexico", "Greece", "Egypt", "India"],
    correctAnswer: 2,
  },
  {
    id: "general-005",
    topic: "general-knowledge",
    category: "Tech",
    difficulty: "medium",
    question: "What does 'HTTP' stand for?",
    options: [
      "HyperText Transfer Protocol",
      "HighText Transmission Program",
      "Hyperlink Transfer Process",
      "Home Tool Transfer Protocol",
    ],
    correctAnswer: 0,
  },
  {
    id: "general-006",
    topic: "general-knowledge",
    category: "Nature",
    difficulty: "easy",
    question: "Which animal is the largest mammal on Earth?",
    options: ["Elephant", "Blue whale", "Giraffe", "Polar bear"],
    correctAnswer: 1,
  },
  {
    id: "general-007",
    topic: "general-knowledge",
    category: "Culture",
    difficulty: "easy",
    question: "How many continents are there?",
    options: ["5", "6", "7", "8"],
    correctAnswer: 2,
  },
  {
    id: "general-008",
    topic: "general-knowledge",
    category: "Math",
    difficulty: "easy",
    question: "What is 25 × 4?",
    options: ["50", "75", "100", "125"],
    correctAnswer: 2,
  },
  {
    id: "general-009",
    topic: "general-knowledge",
    category: "Space",
    difficulty: "medium",
    question: "What is the name of our galaxy?",
    options: ["Andromeda", "Milky Way", "Whirlpool", "Sombrero"],
    correctAnswer: 1,
  },
  {
    id: "general-010",
    topic: "general-knowledge",
    category: "Health",
    difficulty: "easy",
    question: "Which vitamin do we get from sunlight?",
    options: ["Vitamin A", "Vitamin B12", "Vitamin C", "Vitamin D"],
    correctAnswer: 3,
  },
  {
    id: "general-011",
    topic: "general-knowledge",
    category: "Sports",
    difficulty: "easy",
    question: "How many players are on a soccer team on the field?",
    options: ["9", "10", "11", "12"],
    correctAnswer: 2,
  },
  {
    id: "general-012",
    topic: "general-knowledge",
    category: "Logic",
    difficulty: "medium",
    question: "Which one is NOT a primary color?",
    options: ["Red", "Blue", "Green", "Yellow"],
    correctAnswer: 2,
  },
{
id: "general-013",
topic: "general-knowledge",
category: "Natural Science",
difficulty: "easy",
question: "What gas do plants absorb from the air during photosynthesis?",
options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"],
correctAnswer: 2,
},
{
id: "general-014",
topic: "general-knowledge",
category: "Biology",
difficulty: "medium",
question: "Which part of the cell contains genetic material (DNA)?",
options: ["Ribosome", "Nucleus", "Cell membrane", "Cytoplasm"],
correctAnswer: 1,
},
{
id: "general-015",
topic: "general-knowledge",
category: "Earth Science",
difficulty: "medium",
question: "What is the main cause of ocean tides on Earth?",
options: [
"Earth’s winds",
"The Moon’s gravitational pull",
"Underwater earthquakes",
"Changes in ocean temperature",
],
correctAnswer: 1,
},
{
id: "general-016",
topic: "general-knowledge",
category: "Chemistry",
difficulty: "medium",
question: "What is the pH of a neutral solution?",
options: ["1", "7", "10", "14"],
correctAnswer: 1,
},
{
id: "general-017",
topic: "general-knowledge",
category: "Physics",
difficulty: "hard",
question: "Which type of electromagnetic wave has the shortest wavelength?",
options: ["Radio waves", "Microwaves", "X-rays", "Visible light"],
correctAnswer: 2,
},
{
id: "general-018",
topic: "general-knowledge",
category: "Biology",
difficulty: "medium",
question: "What is the role of red blood cells in the human body?",
options: [
"Fighting infections",
"Carrying oxygen",
"Producing hormones",
"Digesting food",
],
correctAnswer: 1,
},
{
id: "general-019",
topic: "general-knowledge",
category: "Astronomy",
difficulty: "hard",
question: "A light-year is a unit of...",
options: ["Time", "Brightness", "Distance", "Mass"],
correctAnswer: 2,
},
{
id: "general-020",
topic: "general-knowledge",
category: "Ecology",
difficulty: "hard",
question: "What term describes a species that strongly affects an ecosystem even if it’s not the most numerous?",
options: ["Invasive species", "Keystone species", "Predator species", "Indicator species"],
correctAnswer: 1,
},
{
id: "general-021",
topic: "general-knowledge",
category: "Earth Science",
difficulty: "medium",
question: "What layer of Earth is responsible for plate tectonics?",
options: ["Inner core", "Outer core", "Mantle (upper mantle/asthenosphere)", "Crust only"],
correctAnswer: 2,
},
{
id: "general-022",
topic: "general-knowledge",
category: "Biology",
difficulty: "hard",
question: "Which process allows organisms to become better suited to their environment over generations?",
options: ["Metabolism", "Natural selection", "Evaporation", "Digestion"],
correctAnswer: 1,
},
{
id: "general-023",
topic: "general-knowledge",
category: "Chemistry",
difficulty: "hard",
question: "What is the most abundant element in Earth’s atmosphere?",
options: ["Oxygen", "Carbon dioxide", "Nitrogen", "Argon"],
correctAnswer: 2,
},
{
id: "general-024",
topic: "general-knowledge",
category: "Physics",
difficulty: "medium",
question: "What term describes the bending of light as it passes from one medium to another?",
options: ["Reflection", "Refraction", "Diffusion", "Radiation"],
correctAnswer: 1,
},
{
id: "general-025",
topic: "general-knowledge",
category: "Astronomy",
difficulty: "medium",
question: "What is a supernova?",
options: [
"A newborn star",
"A star’s explosive death",
"A type of comet",
"A black hole feeding",
],
correctAnswer: 1,
},
{
id: "general-026",
topic: "general-knowledge",
category: "Ecology",
difficulty: "medium",
question: "Which biome is characterized by very low rainfall and extreme temperatures?",
options: ["Tundra", "Rainforest", "Desert", "Taiga"],
correctAnswer: 2,
},
{
id: "general-027",
topic: "general-knowledge",
category: "Biology",
difficulty: "hard",
question: "What do mitochondria primarily do in a cell?",
options: [
"Store water",
"Produce energy (ATP)",
"Make proteins",
"Control cell division",
],
correctAnswer: 1,
},
{
id: "general-028",
topic: "general-knowledge",
category: "Earth Science",
difficulty: "hard",
question: "What is the name of the process in which water vapor turns directly into ice without becoming liquid?",
options: ["Condensation", "Sublimation", "Deposition", "Evaporation"],
correctAnswer: 2,
},
{
id: "general-029",
topic: "general-knowledge",
category: "Zoology",
difficulty: "medium",
question: "Which group of animals is cold-blooded and usually has scales?",
options: ["Mammals", "Reptiles", "Birds", "Amphibians"],
correctAnswer: 1,
},
{
id: "general-030",
topic: "general-knowledge",
category: "Ocean Science",
difficulty: "hard",
question: "What is the deepest part of the world’s oceans called?",
options: ["Mariana Trench", "Mid-Atlantic Ridge", "Great Barrier Reef", "Bering Strait"],
correctAnswer: 0,
},
{
id: "general-031",
topic: "general-knowledge",
category: "Climate Science",
difficulty: "hard",
question: "Which greenhouse gas is the largest contributor to human-caused global warming?",
options: ["Methane", "Carbon dioxide", "Ozone", "Water vapor"],
correctAnswer: 1,
},
{
id: "general-032",
topic: "general-knowledge",
category: "Geology",
difficulty: "medium",
question: "Igneous rocks form when...",
options: [
"Sediments are compressed",
"Magma or lava cools and solidifies",
"Rocks are changed by heat and pressure",
"Water evaporates from minerals",
],
correctAnswer: 1,
},

  // =========================
  // SOFT SKILLS
  // =========================
  {
    id: "soft-001",
    topic: "soft-skills",
    category: "Communication",
    difficulty: "easy",
    question: "Which phrase is most appropriate for asking for feedback from your manager?",
    options: [
      "Give me your thoughts.",
      "Tell me what you think.",
      "I would appreciate your feedback on this.",
      "What do you think about it?",
    ],
    correctAnswer: 2,
  },
  {
    id: "soft-002",
    topic: "soft-skills",
    category: "Communication",
    difficulty: "easy",
    question: "Which sentence demonstrates active listening?",
    options: [
      "I understand your point. Let me repeat it to be sure.",
      "You are wrong about that.",
      "Let me tell you what I think.",
      "I wasn’t paying attention, can you repeat?",
    ],
    correctAnswer: 0,
  },
  {
    id: "soft-003",
    topic: "soft-skills",
    category: "Meetings",
    difficulty: "easy",
    question: "Which is the most professional way to disagree in a meeting?",
    options: [
      "That's not right.",
      "I don't think so.",
      "I see your point; however, I have a different view.",
      "You're mistaken.",
    ],
    correctAnswer: 2,
  },
  {
    id: "soft-004",
    topic: "soft-skills",
    category: "Teamwork",
    difficulty: "easy",
    question: "A good team member should usually...",
    options: [
      "Work alone so things stay consistent",
      "Share information and support others",
      "Avoid asking questions",
      "Only do their part and stop",
    ],
    correctAnswer: 1,
  },
  {
    id: "soft-005",
    topic: "soft-skills",
    category: "Time Management",
    difficulty: "medium",
    question: "What is the best way to handle too many tasks?",
    options: [
      "Ignore the hardest ones",
      "Do everything at the last minute",
      "Prioritize and plan your time",
      "Wait until someone helps",
    ],
    correctAnswer: 2,
  },
  {
    id: "soft-006",
    topic: "soft-skills",
    category: "Feedback",
    difficulty: "medium",
    question: "Good feedback should be...",
    options: [
      "Vague so it doesn’t hurt feelings",
      "Specific and focused on behavior",
      "Only negative",
      "Only positive",
    ],
    correctAnswer: 1,
  },
  {
    id: "soft-007",
    topic: "soft-skills",
    category: "Workplace",
    difficulty: "easy",
    question: "Being 'proactive' at work means...",
    options: [
      "Waiting for full instructions",
      "Acting in advance without being asked",
      "Doing nothing until a problem happens",
      "Avoiding responsibility",
    ],
    correctAnswer: 1,
  },
  {
    id: "soft-008",
    topic: "soft-skills",
    category: "Conflict",
    difficulty: "medium",
    question: "When a conflict starts, a helpful first step is to...",
    options: [
      "Raise your voice",
      "Listen and clarify the issue",
      "Blame someone quickly",
      "Leave the team",
    ],
    correctAnswer: 1,
  },
  {
    id: "soft-009",
    topic: "soft-skills",
    category: "Collaboration",
    difficulty: "easy",
    question: "Collaboration is best described as...",
    options: [
      "Working together to reach a goal",
      "Competing to be first",
      "Working without sharing",
      "Avoiding teamwork",
    ],
    correctAnswer: 0,
  },
  {
    id: "soft-010",
    topic: "soft-skills",
    category: "Mindset",
    difficulty: "easy",
    question: "A growth mindset means you believe skills...",
    options: [
      "Never change",
      "Can improve with effort",
      "Only matter if you’re talented",
      "Are not important",
    ],
    correctAnswer: 1,
  },
  {
    id: "soft-011",
    topic: "soft-skills",
    category: "Professionalism",
    difficulty: "medium",
    question: "Professional emails should usually be...",
    options: [
      "Short and rude",
      "Clear, polite, and structured",
      "Full of emojis",
      "Written like texting",
    ],
    correctAnswer: 1,
  },
  {
    id: "soft-012",
    topic: "soft-skills",
    category: "Decision Making",
    difficulty: "medium",
    question: "A good decision is often based on...",
    options: [
      "Guessing fast",
      "Data and reasoning",
      "What feels coolest",
      "Avoiding responsibility",
    ],
    correctAnswer: 1,
  },
{
id: "soft-013",
topic: "soft-skills",
category: "Communication",
difficulty: "medium",
question: "Which approach is best for giving constructive criticism to a teammate?",
options: [
"Point out mistakes in front of everyone so they learn faster",
"Focus on the person’s character to explain the issue",
"Describe the behavior, explain impact, and suggest a next step",
"Avoid mentioning the problem to keep things friendly",
],
correctAnswer: 2,
},
{
id: "soft-014",
topic: "soft-skills",
category: "Leadership",
difficulty: "hard",
question: "You notice a quiet teammate has a strong idea but isn’t speaking up. What is the best leadership move?",
options: [
"Move on quickly to keep the meeting on schedule",
"Ask them directly for their thoughts and create space to share",
"Assume they’ll email you later if it matters",
"Speak for them based on what you think they mean",
],
correctAnswer: 1,
},
{
id: "soft-015",
topic: "soft-skills",
category: "Conflict",
difficulty: "hard",
question: "Two teammates disagree strongly about a solution. What is the most effective first step to mediate?",
options: [
"Pick a side to end the argument",
"Ask each person to explain their reasoning and goals",
"Tell them to stop discussing it",
"Escalate immediately to your manager",
],
correctAnswer: 1,
},
{
id: "soft-016",
topic: "soft-skills",
category: "Time Management",
difficulty: "hard",
question: "Which is the best example of prioritizing work using impact and urgency?",
options: [
"Do quick tasks first because they feel easier",
"Work on tasks in the order they arrived",
"Start with tasks that are high-impact and time-sensitive",
"Wait to see what your manager mentions next",
],
correctAnswer: 2,
},
{
id: "soft-017",
topic: "soft-skills",
category: "Emotional Intelligence",
difficulty: "hard",
question: "A colleague seems unusually short in messages today. What's the best response?",
options: [
"Assume they’re mad at you and avoid them",
"Reply with the same tone to match energy",
"Check in politely and focus on facts, not assumptions",
"Report them for being unprofessional",
],
correctAnswer: 2,
},
{
id: "soft-018",
topic: "soft-skills",
category: "Adaptability",
difficulty: "medium",
question: "A project changes direction after new information arrives. What’s the healthiest reaction?",
options: [
"Stick to the original plan to avoid confusion",
"Complain that changes are unfair",
"Ask what changed, update your plan, and move forward",
"Wait until you’re told exactly what to do",
],
correctAnswer: 2,
},
{
id: "soft-019",
topic: "soft-skills",
category: "Meetings",
difficulty: "hard",
question: "Which meeting behavior most improves decision-making?",
options: [
"Letting the most senior person talk first",
"Sharing your view early and inviting quieter voices",
"Avoiding disagreement to keep things smooth",
"Focusing on minor details before goals",
],
correctAnswer: 1,
},
{
id: "soft-020",
topic: "soft-skills",
category: "Collaboration",
difficulty: "hard",
question: "What’s the best way to handle overlapping responsibilities in a team?",
options: [
"Assume others will handle it",
"Compete to show who is better",
"Clarify ownership, deadlines, and communication upfront",
"Wait until a conflict happens to discuss it",
],
correctAnswer: 2,
},
{
id: "soft-021",
topic: "soft-skills",
category: "Feedback",
difficulty: "hard",
question: "What is the most useful way to receive feedback you disagree with?",
options: [
"Reject it immediately and defend yourself",
"Listen, ask for examples, and decide what to apply",
"Ignore it because you know your work best",
"Tell others the feedback was unfair",
],
correctAnswer: 1,
},
{
id: "soft-022",
topic: "soft-skills",
category: "Decision Making",
difficulty: "hard",
question: "When making a tough decision with incomplete data, a good practice is to...",
options: [
"Wait forever until data is perfect",
"Choose based only on your gut feeling",
"Identify assumptions, assess risks, and pick a reversible option if possible",
"Ask someone else to decide for you",
],
correctAnswer: 2,
},
{
id: "soft-023",
topic: "soft-skills",
category: "Professionalism",
difficulty: "medium",
question: "Which email opening is best for a sensitive clarification?",
options: [
"You messed this up.",
"Just checking — can you clarify what you meant by...?",
"Why would you say that?",
"This makes no sense.",
],
correctAnswer: 1,
},
{
id: "soft-024",
topic: "soft-skills",
category: "Negotiation",
difficulty: "hard",
question: "You need more time for a task. What is the strongest way to negotiate?",
options: [
"Say you can’t do it and stop responding",
"Explain your current workload, propose a new deadline, and offer trade-offs",
"Wait until the deadline passes to mention it",
"Ask a teammate to do it without telling anyone",
],
correctAnswer: 1,
},
{
id: "soft-025",
topic: "soft-skills",
category: "Remote Work",
difficulty: "hard",
question: "In remote collaboration, what most reduces misunderstandings?",
options: [
"Assuming everyone reads your mind",
"Over-communicating goals, context, and next steps in writing",
"Only using short messages",
"Avoiding video calls entirely",
],
correctAnswer: 1,
},
{
id: "soft-026",
topic: "soft-skills",
category: "Ethics",
difficulty: "hard",
question: "You notice a small error in a report that makes results look better than they are. What should you do?",
options: [
"Leave it, since it benefits the team",
"Fix it and inform relevant stakeholders",
"Wait to see if someone else catches it",
"Delete the report",
],
correctAnswer: 1,
},
{
id: "soft-027",
topic: "soft-skills",
category: "Stress Management",
difficulty: "medium",
question: "Which strategy is most effective for handling work stress long-term?",
options: [
"Ignoring stress until it goes away",
"Working more hours to push through",
"Breaking tasks into chunks and using recovery time",
"Avoiding all challenging tasks",
],
correctAnswer: 2,
},
{
id: "soft-028",
topic: "soft-skills",
category: "Teamwork",
difficulty: "hard",
question: "A teammate misses a deadline that affects your work. What’s the best response?",
options: [
"Blame them publicly so it doesn’t happen again",
"Redo their work without telling them",
"Ask what happened, align on a recovery plan, and adjust expectations",
"Cut them out of future projects",
],
correctAnswer: 2,
},
{
id: "soft-029",
topic: "soft-skills",
category: "Problem Solving",
difficulty: "hard",
question: "What is the best first step when facing a complex problem?",
options: [
"Start solving immediately without context",
"Define the problem clearly and gather key facts",
"Ask someone else to take over",
"Look for a quick fix only",
],
correctAnswer: 1,
},
{
id: "soft-030",
topic: "soft-skills",
category: "Communication",
difficulty: "hard",
question: "Which is the best example of assertive (not aggressive) communication?",
options: [
"You never listen to me.",
"I’d like to share a different perspective and here’s why.",
"Whatever, do what you want.",
"This is a stupid idea.",
],
correctAnswer: 1,
},

  // =========================
  // MEMES & IDIOMS
  // =========================
 {
id: "idioms-013",
topic: "memes-idioms",
category: "Idioms",
difficulty: "hard",
question: 'What does "bite off more than you can chew" mean?',
options: [
"To eat too quickly",
"To take on more responsibility than you can handle",
"To refuse extra work",
"To multitask successfully",
],
correctAnswer: 1,
},
{
id: "idioms-014",
topic: "memes-idioms",
category: "Idioms",
difficulty: "hard",
question: 'If someone says "cutting corners," they mean...',
options: [
"Taking a shorter route home",
"Skipping important steps to save time or money",
"Improving quality carefully",
"Decorating a room",
],
correctAnswer: 1,
},
{
id: "idioms-015",
topic: "memes-idioms",
category: "Idioms",
difficulty: "hard",
question: 'What does "the fine print" refer to?',
options: [
"A stylish font",
"Small details in an agreement that are easy to miss",
"A final draft of a novel",
"A printer error",
],
correctAnswer: 1,
},
{
id: "idioms-016",
topic: "memes-idioms",
category: "Idioms",
difficulty: "hard",
question: 'To "move the goalposts" means to...',
options: [
"Change the rules or expectations after progress is made",
"Finish a task early",
"Help someone succeed",
"Start a new sport",
],
correctAnswer: 0,
},
{
id: "idioms-017",
topic: "memes-idioms",
category: "Idioms",
difficulty: "hard",
question: 'If a plan is "up in the air," it is...',
options: [
"Guaranteed to happen",
"Still uncertain or not decided",
"Very expensive",
"Already finished",
],
correctAnswer: 1,
},
{
id: "idioms-018",
topic: "memes-idioms",
category: "Sayings",
difficulty: "hard",
question: 'What does "don’t put all your eggs in one basket" suggest?',
options: [
"Focus on one big goal only",
"Avoid relying on a single option; spread risk",
"Cook carefully",
"Keep secrets from others",
],
correctAnswer: 1,
},
{
id: "idioms-019",
topic: "memes-idioms",
category: "Idioms",
difficulty: "hard",
question: 'To be "on the fence" about something means to...',
options: [
"Be completely sure",
"Be undecided",
"Be excited",
"Be late",
],
correctAnswer: 1,
},
{
id: "idioms-020",
topic: "memes-idioms",
category: "Idioms",
difficulty: "hard",
question: 'If someone "pulls rank," they...',
options: [
"Quit their job",
"Use their higher status to get their way",
"Make a joke",
"Avoid responsibility",
],
correctAnswer: 1,
},
{
id: "idioms-021",
topic: "memes-idioms",
category: "Idioms",
difficulty: "hard",
question: 'What does "read the room" mean?',
options: [
"Study in a quiet place",
"Notice and adapt to people’s feelings or reactions",
"Clean up a space",
"Look for hidden notes",
],
correctAnswer: 1,
},
{
id: "idioms-022",
topic: "memes-idioms",
category: "Idioms",
difficulty: "hard",
question: 'To "hit the ground running" means to...',
options: [
"Start quickly and effectively",
"Fail immediately",
"Avoid work",
"Exercise before work",
],
correctAnswer: 0,
},
{
id: "idioms-023",
topic: "memes-idioms",
category: "Idioms",
difficulty: "hard",
question: 'If something is "second nature," it is...',
options: [
"Hard to learn",
"Something you do automatically without thinking",
"A brand-new hobby",
"Only for experts",
],
correctAnswer: 1,
},
{
id: "idioms-024",
topic: "memes-idioms",
category: "Sayings",
difficulty: "hard",
question: 'What does "the devil is in the details" mean?',
options: [
"Details are unimportant",
"Small details can cause big problems",
"Evil people like paperwork",
"Plans always go smoothly",
],
correctAnswer: 1,
},
{
id: "idioms-025",
topic: "memes-idioms",
category: "Idioms",
difficulty: "hard",
question: 'To "take something with a grain of salt" means to...',
options: [
"Believe it completely",
"Be slightly skeptical about it",
"Ignore it forever",
"Write it down carefully",
],
correctAnswer: 1,
},
{
id: "idioms-026",
topic: "memes-idioms",
category: "Idioms",
difficulty: "hard",
question: 'If someone is "barking up the wrong tree," they are...',
options: [
"Looking in the wrong place or blaming the wrong person",
"Winning an argument",
"Making a smart guess",
"Being very quiet",
],
correctAnswer: 0,
},
{
id: "idioms-027",
topic: "memes-idioms",
category: "Idioms",
difficulty: "hard",
question: 'What does "throw someone under the bus" mean?',
options: [
"Help them quickly",
"Blame or sacrifice them to protect yourself",
"Surprise them with kindness",
"Invite them to a trip",
],
correctAnswer: 1,
},
{
id: "idioms-028",
topic: "memes-idioms",
category: "Sayings",
difficulty: "hard",
question: 'What does "actions speak louder than words" suggest?',
options: [
"Talking is better than doing",
"What you do matters more than what you say",
"Words are always lies",
"Silence is best",
],
correctAnswer: 1,
},
{
id: "idioms-029",
topic: "memes-idioms",
category: "Idioms",
difficulty: "hard",
question: 'If you "call someone’s bluff," you...',
options: [
"Ignore them",
"Challenge them to prove their threat or claim",
"Agree immediately",
"Tell a joke",
],
correctAnswer: 1,
},
{
id: "idioms-030",
topic: "memes-idioms",
category: "Idioms",
difficulty: "hard",
question: 'To "keep someone in the loop" means to...',
options: [
"Confuse them",
"Keep them informed and included",
"Tell them a secret only",
"Make them wait",
],
correctAnswer: 1,
},
{
id: "idioms-031",
topic: "memes-idioms",
category: "Riddles",
difficulty: "hard",
question: "I’m tall when I’m young and short when I’m old. What am I?",
options: ["A candle", "A tree", "A shadow", "A pencil"],
correctAnswer: 0,
},
{
id: "idioms-032",
topic: "memes-idioms",
category: "Riddles",
difficulty: "hard",
question: "What has hands but can’t clap (and no, it’s not your little brother)?",
options: ["A clock", "A robot", "A chair", "A crab"],
correctAnswer: 0,
},
{
id: "idioms-033",
topic: "memes-idioms",
category: "Riddles",
difficulty: "hard",
question: "I have a neck but no head, and I wear a cap. What am I?",
options: ["A bottle", "A shirt", "A giraffe", "A pen"],
correctAnswer: 0,
},
{
id: "idioms-034",
topic: "memes-idioms",
category: "Riddles",
difficulty: "hard",
question: "The more you take away from me, the bigger I get. What am I?",
options: ["A hole", "A debt", "A balloon", "A sandwich"],
correctAnswer: 0,
},
{
id: "idioms-035",
topic: "memes-idioms",
category: "Riddles",
difficulty: "hard",
question: "I’m full of keys but I can’t open any doors. What am I?",
options: ["A keyboard", "A map", "A piano bench", "A locker"],
correctAnswer: 0,
},
{
id: "idioms-036",
topic: "memes-idioms",
category: "Riddles",
difficulty: "hard",
question: " What can travel around the world while staying in one corner?",
options: ["A stamp", "A suitcase", "A rumor", "A satellite"],
correctAnswer: 0,
},
{
id: "idioms-037",
topic: "memes-idioms",
category: "Riddles",
difficulty: "hard",
question: "I have one eye but can’t see. What am I?",
options: ["A needle", "A potato", "A hurricane", "A cyclops"],
correctAnswer: 0,
},
{
id: "idioms-038",
topic: "memes-idioms",
category: "Riddles",
difficulty: "hard",
question: "What goes up but never comes down?",
options: ["Your age", "A balloon", "Smoke", "A yo-yo"],
correctAnswer: 0,
},
{
id: "idioms-039",
topic: "memes-idioms",
category: "Riddles",
difficulty: "hard",
question: "I can be cracked, made, told, and played. What am I?",
options: ["A joke", "A violin", "An egg", "A rule"],
correctAnswer: 0,
},
{
id: "idioms-040",
topic: "memes-idioms",
category: "Riddles",
difficulty: "hard",
question: "What has a thumb and four fingers but isn’t alive?",
options: ["A glove", "A statue", "A leaf", "A handprint"],
correctAnswer: 0,
},
{
id: "idioms-041",
topic: "memes-idioms",
category: "Riddles",
difficulty: "hard",
question: " What has to be broken before you can use it?",
options: ["An egg", "A promise", "A phone", "A pencil"],
correctAnswer: 0,
},
{
id: "idioms-042",
topic: "memes-idioms",
category: "Riddles",
difficulty: "hard",
question: " I’m light as a feather, but even the strongest person can’t hold me for long. What am I?",
options: ["Your breath", "A cloud", "A bubble", "A flashlight"],
correctAnswer: 0,
}
]
